# Generated by Django 5.0.4 on 2025-06-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LICENCIA', 'Licencia'), ('PERMISO', 'Permiso'), ('SERVICIO', 'Servicio Público')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.IntegerField(default=0)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.ciudadano')),
            ],
        ),
        migrations.CreateModel(
            name='TramiteMLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad_predicha', models.IntegerField()),
                ('congestion_predicha', models.FloatField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite')),
            ],
        ),
    ]
