# Generated by Django 5.0.4 on 2025-06-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='tramite',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TramiteMLPrediction',
        ),
    ]
